### ISSUE TITLE
Estrutura do README.md

### ISSUE THREAD

**Issue by marcelovbm** [mariazevedo88/financial-java-api#2]
## Descrição
@mariazevedo88 , olhando a documentação descrita no repositório, notei que os campos que estão estruturados como `código` não possuem a definição da linguagem. 

Utilizando [markdown](https://daringfireball.net/projects/markdown/) é possível informar qual a linguagem do código e com isso deixar a documentação melhor visivelmente. 

## Exemplos
```json
{
  "nsu": "123456",
  "authorizationNumber": "010203",
  "amount": "22.88",
  "transactionDate": "2020-04-05T09:59:51.312Z",
  "type": "CARD",
}
```

```bash
mvn package
```

```sql
CREATE database financial;
```

```java
if ( StringUtils.isEmpty(coffee)) {
  return "I WANT MORE!!!!!!";
}
```

**Comment by mariazevedo88** [comment]
Corrigido no pull-request #3. Obrigada, @marcelovbm!
